# Generated by Django 5.1.1 on 2024-09-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='country_of_manufacture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور سازنده'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام برند'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='nationality',
            field=models.CharField(max_length=100, verbose_name='ملیت برند'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_inventory.brand', verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_inventory.color', verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='phone_images', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='موجود/ناموجود'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='model',
            field=models.CharField(max_length=100, unique=True, verbose_name='مدل'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='screen_size',
            field=models.FloatField(verbose_name='سایز صفحه نمایش'),
        ),
    ]
