# Generated by Django 5.1.1 on 2024-09-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0003_country_alter_brand_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='country_of_manufacture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobile_inventory.country', verbose_name='کشور سازنده'),
        ),
    ]
