# Generated by Django 5.1.1 on 2024-09-30 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0004_alter_phone_country_of_manufacture'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
