# Generated by Django 5.1.1 on 2024-09-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_inventory', '0006_brand_created_at_color_created_at_country_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='آدرس برند'),
        ),
        migrations.AddField(
            model_name='color',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='آدرس رنگ'),
        ),
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='آدرس کشور'),
        ),
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='آدرس محصول'),
        ),
    ]
