version: '3'

services:
  web:
    build: .
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
   ports:
  - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: mobilestore_db
      POSTGRES_USER: store_user
      POSTGRES_PASSWORD: mobilestore1234
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
